#!/bin/sh

### BEGIN INIT INFO
# Provides:          fastresize
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the fastresize FastCGI backend
# Description:       Starts the fastresize FastCGI backend
### END INIT INFO
# Author: Lukas Martini <lutoma@phoria.eu>

DAEMON=/usr/bin/fastresize
SERVICE_NAME=fastresize
USER=app
GROUP=app
PIDFILE=/var/run/fastresize.pid
DAEMON_OPTS="/var/www/asset/ 127.0.0.1:9000 nginx nginx 9"

if [ ! -x $DAEMON ]; then
  echo "ERROR: Can't execute $DAEMON."
  exit 1
fi

if [ ! -d $SERVICE_DIR ]; then
  echo "ERROR: Directory doesn't exist: $SERVICE_DIR"
  exit 1
fi

start_service() {
  echo -n " * Starting $SERVICE_NAME... "
  start-stop-daemon -Sq -p $PIDFILE -x $DAEMON -- $DAEMON_OPTS
  e=$?
  if [ $e -eq 1 ]; then
    echo "Couldn't start, see syslog for details"
    return
  fi
}

stop_service() {
  echo -n " * Stopping $SERVICE_NAME... "
  #start-stop-daemon -Kq -R 10 -p $PIDFILE
  #e=$?
  #if [ $e -eq 1 ]; then
  #  echo "not running"
  #  return
  #fi
  
  # FIXME
  killall $DAEMON 
  echo "done"
}

case "$1" in
  start)
    start_service
    ;;
  stop)
    stop_service
    ;;
  restart)
    stop_service
    start_service
    ;;
  *)
    echo "Usage: /etc/init.d/$SERVICE_NAME {start|stop|restart}" >&2
    exit 1   
    ;;
esac

exit 0
